name: Build and Publish package
on:
  push:
    branches: [OB-913]
  workflow_dispatch:

jobs:
  build-publish-package:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean install

      - name: Build docker image
        run: docker build -t dhis2-integration:latest -f package/docker/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'dhis2-integration:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.MALAYSIA_LITE_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MALAYSIA_LITE_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.MALAYSIA_LITE_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image tag varaible
        run: echo "ARTIFACT_VERSION=$(cat package/.appversion)-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Tag and Push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: msf-oca-his/dhis2-integration
          IMAGE_TAG: ${{ env.ARTIFACT_VERSION }}
        run: |
          docker tag dhis2-integration:latest $REGISTRY/$REPOSITORY:latest
          docker tag dhis2-integration:latest $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:latest
